[package]
name = "onenote-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
publish = false

[dependencies]
blake3.workspace = true
onenote_parser.workspace = true
serde.workspace = true
thiserror.workspace = true
typed-path.workspace = true
uuid.workspace = true

[dev-dependencies]
serde_json.workspace = true
tempfile.workspace = true

[lints]
workspace = true
