[package]
name = "onenote-render-gtk"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
publish = false

[dependencies]
anyhow.workspace = true
gtk.workspace = true
image.workspace = true
num-traits.workspace = true
onenote-core.workspace = true
onenote-render.workspace = true
typst.workspace = true
typst-as-lib.workspace = true
typst-assets.workspace = true
typst-render.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
