[package]
name = "onenote-render"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
publish = false

[dependencies]
onenote-core.workspace = true
serde.workspace = true
thiserror.workspace = true

[lints]
workspace = true
